### ISSUE TITLE
Problems of the async loading implementation

### ISSUE THREAD

**Issue by haowang1013** [rdeioris/glTFRuntime#94]
Hi,

I'm playing with the async version of the asset loading APIs and it's crashing for me all over the places.
After checking the code it seems the implementation simply runs the loading code in a task thread without having any race protection of the internal properties (FglTFRuntimeParser has loads and loads of properties all touched along the asset loading code path).
Also, I don't think it's even safe to construct unreal objects in a non-game thread, which the loading code path will surely do.

Am I missing something obvious here or are the async APIs simply not properly implemented?

Thanks

**Comment by rdeioris** [comment]
Hi, from your report it looks like you are assuming "parallelism" instead of pure background loading. The api is meant for chain-loading (look at https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Private/glTFRuntimeAssetActorAsync.cpp for an example usage). Basically the loading is split in two phases, the first one where the non-uobject related structures are managed (parsing and filtering) in a new thread and a second one where the "finalization" happens (read: uobjects are filled) and it is executed in the main thread using the task graph (check the LoadAsRuntimeLODAsync template function). There is a pretty heavy cost in terms of pure performances with this approach, but instead of putting locks basically everywhere in the code (making it super-complex and error prone) that latest tendency in in using ParallelFor whenever possible.
On the discord server you may find multiple discussions about improving parallelism and there is even a pull request improving the async actor by removing the tick-dependency and putting a big-lock on the parser (that is suboptimal but it makes the loading way faster)

**Comment by haowang1013** [comment]
Thanks, the APIs I played with are the LoadXXXAsync in UglTFRuntimeAsset, we're not using the asset actor at all.

For instance, look at `FglTFRuntimeParser::LoadSkeletalMeshAsync`, it does the entire loading logic in a task thread and it would suffer the problem I mentioned above, no?

**Comment by rdeioris** [comment]
Nope, look at the FglTFRuntimeSkeletalMeshContextFinalizer, it is where the UObject managament is managed in the taskgraph. (basically it happens after the CreateSkeletalMeshFromLODs() call)

**Comment by haowang1013** [comment]
Took me a long time to figured out what really happened, so it is a race condition problem but it's not what I thought it was.

Basically we're making 2 `LoadStaticMeshAsync` calls in quick succession, on the same UglTFRuntimeAsset.
This causes 2 parallel loading tasks to run at the same time and since there's no locking of the state of UglTFRuntimeAsset, things got messed up and we got a crash of using freed memory - in this particular case it's `FglTFRuntimeParser::LODsCache`

One could argue that this is a "bug" of the application code but IMO the plugin should deal with it better. Even logging an error and rejecting the second call would be 100 times better than a random crash.

**Comment by rdeioris** [comment]
I would not say it is a "bug" in the application (or in the plugin), it is just the expected behaviour for an unsupported operation (you could argue that unreal itself should deal with it, but when dealing with threads it is common to define boundaries in the usage instead of adding complex logic). I will add a section in the docs about the async functions and how they are supposed to be used (as currently everything is basically only in the discord server).
